package searchengine

import (
	"KeywordCollection/chrome"
	"github.com/tebeka/selenium"
)

// SearchEngine ...
type WebSearchEngine interface {
	// Start ...
	Start(word *SearchWord) error
	// Search ...
	Search() error
	// SearchChrome ...
	SearchChrome() error
	// SetOpt ...
	SetOpt(opt *SearchOption)
	// SetChrome ...
	SetChrome(chrome *chrome.ChromeDriver)
	// Close ...
	Close()
	// Opt ...
	Opt() *SearchOption
	// Word ...
	Word() *SearchWord
	// WebBrowser ...
	WebBrowser() selenium.WebDriver
}

// WebSearchStore ...
type WebSearchStore interface {
	// Store ...
	Store(value map[string]interface{}) error
	// Close ...
	Close()
	// Foreach ...
	Foreach(fn func(index int, data *StoreItem) bool)
	// Top ...
	Top(n int) (string, error)
	// Length ...
	Length() int
}
